# 세션 시간 설정
server.servlet.session.timeout=21600

#톰켓설정
#css 파일등을 압축 옵션
server.compression.enabled=true
#서버 정보이름 변경
server.server-header=server
server.error.whitelabel.enabled=false
server.error.path=/error/errorIntro.do

# thymeleaf
spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

#개발
#spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.hikari.jdbc-url=jdbc:mariadb://localhost:3306/sevenbricks
#spring.datasource.hikari.username=root
#spring.datasource.hikari.password=1234

#본서버
spring.datasource.hikari.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mariadb://222.239.169.197:3306/sevenbricks
spring.datasource.hikari.username=sevenbricks
spring.datasource.hikari.password=dosxlahqkdlf%^78

# MyBatis
mybatis.type-aliases-package=com.sevenbricks
mybatis.mapper-locations=mybatis/mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
